export default {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAIL: 'FETCH_INGREDIENTS_FAIL',
    PURCHASE_BURGUER_START: 'PURCHASE_BURGUER_START',
    PURCHASE_BURGUER_SUCCESS: 'PURCHASE_BURGUER_SUCCESS',
    PURCHASE_BURGUER_FAIL: 'PURCHASE_BURGUER_FAIL',
};
